// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigInterface is an autogenerated mock type for the ConfigInterface type
type ConfigInterface struct {
	mock.Mock
}

// ConfigPath provides a mock function with given fields:
func (_m *ConfigInterface) ConfigPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DefaultConfigPath provides a mock function with given fields:
func (_m *ConfigInterface) DefaultConfigPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ReadConfig provides a mock function with given fields: path, cfg
func (_m *ConfigInterface) ReadConfig(path string, cfg interface{}) error {
	ret := _m.Called(path, cfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(path, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
